version: '3'
services:
    
  server:
     build:
      dockerfile: Dockerfile.dev
      context: ./server
     volumes:
      - /app/node_modules
      - ./server:/app
     ports:  
      - 3000:3000
   
  client:
     build:
      dockerfile: Dockerfile.dev
      context: ./client
     volumes:
      - /app/node_modules
      - ./client:/app
     ports:  
      - 8080:8080
      